### ISSUE TITLE
Should you force QT_QPA_PLATFORM=xcb

### ISSUE THREAD

**Issue by detrout** [flathub/org.kde.kontact#3]
qt-webkit doesn't work very well (if at all) under wayland.

Maybe the run_kontact.sh script should force using xcb for now?

**Comment by danvratil** [comment]
We use QtWebEngine, which should work under Wayland (?), although  I don't know how well (and how big role Flatpak plays in it).

The second thing I don't know is if I can actually force XCB this way because inside of Flatpak Qt applications are using some special QPA plugin.

@grulja (hi! :smile: ), can I set the QT_QPA_PLATFORM without breaking the Flatpak QPA and portals?

**Comment by detrout** [comment]
If I run like this: `flatpak run org.kde.kontact/x86_64/stable`

I get this.

![flatpak-contact-wayland](https://user-images.githubusercontent.com/975038/46379601-182db000-c654-11e8-865e-a681f283bea7.png)

If I run like it like this: `QT_QPA_PLATFORM=xcb flatpak run org.kde.kontact/x86_64/stable`

![flatpak-kontact-xcb](https://user-images.githubusercontent.com/975038/46380015-9c346780-c655-11e8-854f-ea22aba0b51a.png)

Debian Testing with wayland, a high dpi laptop panel and a low resolution external panel connected via VGA. kwin-wayland 4:5.13.5-1

**Comment by detrout** [comment]
It is kind of a hack, but it avoids a really bad user experience. Mostly someone just needs to remember to remove it when WebKit gets fixed.

**Comment by eszlari** [comment]
You could add `--env=QT_QPA_PLATFORM=xcb` to `finish-args` in the manifest.

**Comment by grulja** [comment]
> The second thing I don't know is if I can actually force XCB this way because inside of Flatpak Qt applications are using some special QPA plugin.
> 
> @grulja (hi!  ), can I set the QT_QPA_PLATFORM without breaking the Flatpak QPA and portals?
You can do that, because most of the portal support is in platform theme. We used to have our own platform plugin, but this was causing lots of issues and it was the main reason why I moved everything to Qt, to have a separated platform theme and support for other portals in Qt code directly (e.g. in QGenericUnixServices), without need to have full custom platform plugin.

**Comment by danvratil** [comment]
Fixed in commit 6d8b56937
